name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      MTA_SERVER_VERSION:
        description: 'MTA Server Version'
        required: true
        default: '1.6.0'
      MTA_SERVER_BUILD_NUMBER:
        description: 'MTA Server Build Number'
        required: true
        default: '22511'
      IMAGE_VERSION:
        description: 'Image Version'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg MTA_SERVER_VERSION=${{ github.event.inputs.MTA_SERVER_VERSION }} \
            --build-arg MTA_SERVER_BUILD_NUMBER=${{ github.event.inputs.MTA_SERVER_BUILD_NUMBER }} \
            -t ghcr.io/${{ github.repository_owner }}/mtasa-server:${{ github.event.inputs.MTA_SERVER_VERSION }}-${{ github.event.inputs.MTA_SERVER_BUILD_NUMBER }}-v${{ github.event.inputs.IMAGE_VERSION }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mtasa-server:${{ github.event.inputs.MTA_SERVER_VERSION }}-${{ github.event.inputs.MTA_SERVER_BUILD_NUMBER }}-v${{ github.event.inputs.IMAGE_VERSION }}
